require('config.lsp')
require('config.lsp.ts_ls')
require('config.lsp.lua_ls')
require('config.opts.opts')
require('config.keymaps')
require('config.diagnostics.diagnostics')
require('config.autocmds.highlight_on_yank')
